"""
Django settings for FCS project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from cryptography.fernet import Fernet
import base64
from dotenv import load_dotenv

# Load .env file (if exists)
load_dotenv()

ENCRYPTION_KEY_ENV_VAR = "ENCRYPTION_KEY"

# Check if ENCRYPTION_KEY is already set
if os.getenv(ENCRYPTION_KEY_ENV_VAR):
    ENCRYPTION_KEY = os.getenv(ENCRYPTION_KEY_ENV_VAR)
else:
    # Generate and store a new ENCRYPTION_KEY only if it doesn't exist
    ENCRYPTION_KEY = base64.urlsafe_b64encode(os.urandom(32)).decode()
    with open(".env", "a") as env_file:
        env_file.write(f"\n{ENCRYPTION_KEY_ENV_VAR}={ENCRYPTION_KEY}")
    os.environ[ENCRYPTION_KEY_ENV_VAR] = ENCRYPTION_KEY

print(f"Using ENCRYPTION_KEY: {ENCRYPTION_KEY}")  # Debugging, remove later
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent




MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nh&bk1uzg)2qj7h^#^&ewv)feka(c85c=q+y75_eritcjm#q97'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# AUTH_USER_MODEL = "users.CustomUser

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'django_cleanup',
    'rest_framework.authtoken',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels',

    # 'django.contrib.sites'

]





CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',  # Use Redis in production
    },
}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "yash22589@iiitd.ac.in"  # Replace with your email
EMAIL_HOST_PASSWORD = "flvg npis otas shva"  # Use an App Password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


api="431377ea50msh00ad7558b08f779p16252bjsna588b43f9005"
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # Use Token-based auth
        # 'rest_framework.authentication.SessionAuthentication',  # Keep Session-based auth
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # Default Django auth
]

# CSRF_TRUSTED_ORIGINS = True
CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins (for development)
# Allow all methods (GET, POST, PUT, DELETE, etc.)
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "OPTIONS"
]


# Ensure that requests are only served over HTTPS
SECURE_SSL_REDIRECT = False  # Redirect HTTP to HTTPS
SECURE_PROXY_SSL_HEADER = None  # Required if behind a proxy/load balancer

# Enable HTTPS cookies
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_NAME = "sessionid_custom"
SESSION_COOKIE_SECURE = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# Use strong security headers
SECURE_HSTS_SECONDS = 0  # Enable HTTP Strict Transport Security (HSTS)
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False




# Allow all headers
CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # Keep this for security
    'corsheaders.middleware.CorsMiddleware',
]





CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React frontend
    "http://127.0.0.1:8000",  # Django backend
]


CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:8000",
]

ROOT_URLCONF = 'FCS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FCS.wsgi.application'
ASGI_APPLICATION = 'FCS.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
