# Generated by Django 5.1.7 on 2025-03-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='text_encrypted',
        ),
    ]
