# Generated by Django 5.1.7 on 2025-03-31 13:59

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_text_message_text_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=users.models.message_media_upload_path),
        ),
        migrations.AddField(
            model_name='message',
            name='media_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='text_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
