# Generated by Django 5.1.7 on 2025-04-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_accountdeactivationrequest_accountdeletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='private_key_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
