# Generated by Django 5.1.7 on 2025-04-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_private_key_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
