# Generated by Django 5.1.7 on 2025-04-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_groupmessage_is_encrypted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='is_encrypted',
        ),
    ]
